config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: %i[create destroy]
  resources :categories
  resources :profiles

  get '/confirm_email/:token', to: 'users#confirm_email'
  delete '/logout', to: "sessions#destroy", as: 'logout'

  post '/login', to: "sessions#create", as: 'new_user_session'
  get '/login', to: "sessions#login", as: 'login'

  delete "/user/:id", to: "users#destroy", as: "user_destroy"
  patch "/user/:id", to: "users#update"
  get "/user/:id/edit", to: "users#edit", as: "user_edit"
  get "/user/:id", to: "users#show", as: "user"
  post '/users', to: "users#create"
  get '/signup', to: "users#new", as: "signup"
  get '/users', to: 'users#index'

  delete "/article/:id", to: "articles#destroy", as: "article_destroy"
  patch "/article/:id", to: "articles#update"
  get "/article/:id/edit", to: "articles#edit", as: "article_edit"
  get "/article/:id", to: "articles#show", as: "article"
  get "/articles/new", to: "articles#new"
  post "/articles", to: "articles#create"
  get "/articles", to: "articles#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :name, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :birth, presence: true
  validates :gender, presence: true
  validate :validate_gender
  belongs_to :user
  enum role: [:member, :admin, :superadmin]
  after_create :set_role

  private

  def validate_gender
    unless self.gender == 'Male' || self.gender == 'Female'
      errors.add(:gender, "was specified incorrectly")
    end
  end

  def set_role
    self.update(role: 0)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :user_has_profile?, only: %i[new create]
  before_action :set_profile, only: %i[ show edit update destroy ]
  before_action :same_profile?, only: %i[edit update destroy]

  def index
    @profiles = Profile.all
  end

  def show
  end

  def new
    @profile = Profile.new
  end

  def edit
  end

  def create
    @profile = current_user.build_profile(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
    end
  end

  private
    def set_profile
      @profile = Profile.find(params[:id])
    end

    def profile_params
      params.require(:profile).permit(:name, :city, :country, :birth, :gender, :role)
    end

    def same_profile?
      redirect_to users_path unless current_user == @profile.user
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<section class="flex flex-col m-20 px-10 border-2 border-gray-200 items-center justify-center rounded-lg">
  <h1 class="main-title"><%= title %></h1>
  <div class="mb-10 w-full">
    <%= form_with(model: profile, class: "flex flex-col w-full") do |form| %>
      <% if profile.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

          <ul>
            <% profile.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= form.label :name, class: "label-form" %>
        <%= form.text_field :name, class: "field-form" %>
      </div>

      <div>
        <%= form.label :city, class: "label-form" %>
        <%= form.text_field :city, class: "field-form" %>
      </div>

      <div>
        <%= form.label :country, class: "label-form" %>
        <%= form.text_field :country, class: "field-form" %>
      </div>

      <div>
        <%= form.label :birth, class: "label-form" %>
        <%= form.date_field :birth, class: "field-form" %>
      </div>

      <div class="flex items-center gap-5">
        <div class="my-auto">
          <%= form.radio_button :gender, "Male" %>
          <%= form.label :gender, "Male", class: "label-form" %>
        </div>
        <div class="my-auto">
          <%= form.radio_button :gender, "Female" %>
          <%= form.label :gender, "Female", class: "label-form" %>
        </div>
      </div>

      <div class="mt-10 flex justify-center items-center">
        <%= form.submit class: "btn-primary bg-green-800" %>
      </div>
    <% end %>
  </div>
</section>

app/views/profiles/_profile.html.erb
<div id="<%= dom_id profile %>" class="big-card">
  <span class="font-bold text-3xl">
    <%= profile.name %>
  </span>

  <span>
    <%= profile.city %>
    <%= profile.country %>
  </span>

  <span>
    <strong>Birth:</strong>
    <%= profile.birth %>
  </span>

  <span>
    <strong>Gender:</strong>
    <%= profile.gender %>
  </span>

  <span>
    <strong>Role:</strong>
    <%= profile.role %>
  </span>

  <% if current_user == profile.user %>
    <div>
      <%= link_to "Edit profile", edit_profile_path(profile), class: "btn-primary bg-green-800" %>
      <%= link_to "Edit account", user_edit_path(profile.user), class: "btn-primary bg-blue-800" %>
    </div>
  <% end %>

  <% if current_user == profile.user || current_user.profile.superadmin? %>
    <div>
      <%= button_to 'Cancel account', user_destroy_path(profile.user), class:"btn-primary bg-red-800",
        method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } } %>
    </div>
  <% end %>

</div>

app/views/profiles/edit.html.erb
<%= render "form", profile: @profile, title: 'Update Profile' %>

app/views/profiles/index.html.erb
<h1>Profiles</h1>

<div id="profiles">
  <% @profiles.each do |profile| %>
    <%= render profile %>
    <p>
      <%= link_to "Show this profile", profile %>
    </p>
  <% end %>
</div>

<%= link_to "New profile", new_profile_path %>

app/views/profiles/new.html.erb
<%= render "form", profile: @profile, title: 'Create Profile' %>

app/views/profiles/show.html.erb
<section class="p-10">
  <%= render @profile %>
</section>

<section>
  <% @profile.user.articles.each do |article| %>
    <div class="m-5 p-5 border-2 border-gray-400 rounded-lg">
      <span class="font-bold text-lg">
        <%= article.name %> <br>
      </span>
      <span class="font-semibold text-sm">
        <%= article.description %>
      </span>
    </div>
  <% end %>
</section>