config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: %i[create destroy]
  resources :categories
  resources :profiles

  get '/confirm_email/:token', to: 'users#confirm_email'
  delete '/logout', to: "sessions#destroy", as: 'logout'

  post '/login', to: "sessions#create", as: 'new_user_session'
  get '/login', to: "sessions#login", as: 'login'

  delete "/user/:id", to: "users#destroy", as: "user_destroy"
  patch "/user/:id", to: "users#update"
  get "/user/:id/edit", to: "users#edit", as: "user_edit"
  get "/user/:id", to: "users#show", as: "user"
  post '/users', to: "users#create"
  get '/signup', to: "users#new", as: "signup"
  get '/users', to: 'users#index'

  delete "/article/:id", to: "articles#destroy", as: "article_destroy"
  patch "/article/:id", to: "articles#update"
  get "/article/:id/edit", to: "articles#edit", as: "article_edit"
  get "/article/:id", to: "articles#show", as: "article"
  get "/articles/new", to: "articles#new"
  post "/articles", to: "articles#create"
  get "/articles", to: "articles#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/article.rb
class Article < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  has_one_attached :avatar
  has_rich_text :body
  has_and_belongs_to_many :categories
  has_many :comments, dependent: :destroy
  belongs_to :user

  private

  def self.add_categories(article, ids)
    ids.each { |id| article.categories << Category.find(id) }
  end

  def self.update_categories(article, ids)
    article.categories.delete_all unless article.categories.empty?
    ids.each { |id| article.categories << Category.find(id) }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :user_is_member?, only: %i[new create edit update destroy]
  before_action :set_article, only: %i[show edit update destroy]
  before_action :same_user?, only: %i[edit update destroy]
  before_action :categories_ids, only: %i[create update]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def show
    @comment = Comment.new
  end

  def edit
  end

  def create
    @article = current_user.articles.build(article_params)
    Article.add_categories(@article, categories_ids) if categories_ids.present?

    if @article.save
      redirect_to articles_path, notice: "Article was created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    Article.update_categories(@article, categories_ids) if categories_ids.present?

    if @article.update(article_params)
      redirect_to article_path(@article)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:name, :description, :avatar, :body)
  end

  def categories_ids
    params[:categories][:ids].reject { |id| id.empty? }
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def same_user?
    redirect_to articles_path if @article.user != current_user && !current_user.profile.superadmin?
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<section class="flex flex-col m-20 px-10 border-2 border-gray-200 items-center justify-center rounded-lg">
  <h1 class="main-title"><%= title %></h1>
  <div class="mb-10 w-full">
    <%= form_with(model: @article, class:"flex flex-col w-full") do |form| %>
      <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
            <% @article.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= form.label :name, 'Insert name: ', class:"label-form" %>
        <%= form.text_field :name, class:"field-form" %>
      </div>
      <div>
        <%= form.label :description, 'Insert desciption: ', class:"label-form" %>
        <%= form.text_field :description, class:"field-form" %>
      </div>
      <div class="my-2">
        <%= form.label :avatar, 'Insert main image: ', class:"label-form" %>
        <%= form.file_field :avatar %>
      </div>
      <div class="my-2">
        <%= form.label :body, 'Insert content: ', class:"label-form" %>
        <%= form.rich_text_area :body %>
      </div>
      <div class="flex flex-col gap-2">
        <span class="font-bold text-sm">Categories.</span>
        <%= collection_check_boxes(:categories, :ids, Category.all, :id, :name) do |b| %>
            <div class="flex items-center gap-2">
          <% if @article.categories.include?(Category.find(b.object.id)) %>
              <%= b.check_box checked: true %>
          <% else %>
              <%= b.check_box %>
          <% end %>
              <%= b.object.name %>
            </div>
        <% end %>
      </div>
      <div class="my-2 flex items-center justify-center">
        <%= form.submit class:"btn-primary bg-green-800" %>
      </div>
    <% end %>
  </div>
</section>

app/views/articles/edit.html.erb
<%= render 'form', title: 'Edit article' %>

app/views/articles/index.html.erb
<section class="m-10 p-5">
  <h1 class="main-title">Articles</h1>

  <% @articles.each do |article| %>
    <div class="my-10 p-10 rounded-lg border-2 border-blue-200 flex flex-col">
      <div>
        <span class="font-bold text-2xl">
          <%= article.name %> <br>
        </span>
        <span class="text-sm font-semibold">
          <%= article.user.email %> <br>
        </span>
        <span class="text-sm">
          <%= article.description %> <br>
        </span>
      </div>
      <span class="my-3">
        <%= link_to 'See more', article_path(article), class: "btn-primary bg-blue-800" %>
      </span>
    </div>
  <% end %>
</section>

app/views/articles/new.html.erb
<%= render 'form', title: 'New Article' %>

app/views/articles/show.html.erb
<section class="m-10 p-10 flex flex-col items-center">
  <h1 class="main-title mb-1"> <%= @article.name %> </h1>
  <div><%= @article.description %></div>

  <div class="flex gap-5 my-2 items-center justify-center">
    <% @article.categories.each do |category| %>
      <span class="bg-blue-100 text-blue-800 text-xs font-semibold rounded-lg p-1">
        <%= category.name %>
      </span>
    <% end %>
  </div>

  <div class="w-96 my-10">
    <%= image_tag(@article.avatar) if @article.avatar.attached? %>
  </div>

  <div class="flex flex-col items-center justify-center text-center">
    <%= @article.body %>
  </div>

  <% unless current_user.profile.member? %>

  <% if current_user == @article.user || current_user.profile.superadmin? %>

  <div class="flex gap-10">
    <%= link_to 'Edit article', article_edit_path(@article), class:"btn-primary bg-blue-800" %>
    <%= button_to 'Delete article', article_destroy_path(@article), class:"btn-primary bg-red-800",
        method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } } %>
  </div>

  <% end %>

  <% end %>

  <div class="w-full">
    <h4 class="font-bold text-lg mt-10">Comments</h4>

    <div class="my-5">
      <% @article.comments.each do |comment| %>
        <%= render 'comments/comment', comment: comment %>
      <% end %>
    </div>
  </div>

  <div class="w-full">
    <h5 class="font-semibold mt-10">Add comment</h5>
    <%= render 'comments/form', {article: @article, comment: @comment} %>
  </div>
</section>