config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: %i[create destroy]
  resources :categories
  resources :profiles

  get '/confirm_email/:token', to: 'users#confirm_email'
  delete '/logout', to: "sessions#destroy", as: 'logout'

  post '/login', to: "sessions#create", as: 'new_user_session'
  get '/login', to: "sessions#login", as: 'login'

  delete "/user/:id", to: "users#destroy", as: "user_destroy"
  patch "/user/:id", to: "users#update"
  get "/user/:id/edit", to: "users#edit", as: "user_edit"
  get "/user/:id", to: "users#show", as: "user"
  post '/users', to: "users#create"
  get '/signup', to: "users#new", as: "signup"
  get '/users', to: 'users#index'

  delete "/article/:id", to: "articles#destroy", as: "article_destroy"
  patch "/article/:id", to: "articles#update"
  get "/article/:id/edit", to: "articles#edit", as: "article_edit"
  get "/article/:id", to: "articles#show", as: "article"
  get "/articles/new", to: "articles#new"
  post "/articles", to: "articles#create"
  get "/articles", to: "articles#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_token :token, length: 50
  validates :email, presence: true

  validates :password, length: { minimum: 6 }, if: :password_present?
  validates :password_confirmation, length: { minimum: 6 }, if: :password_present?

  has_secure_password
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :profile, dependent: :destroy

  private

  def password_present?
    false || password.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[new create confirm_email]
  before_action :set_user, only: %i[show edit update destroy]
  before_action :same_user?, only: %i[edit update destroy]

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def new
    @user = User.new
  end

  def confirm_email
    user = User.find_by(token: params[:token])
    user.update!(is_confirmed?: true)
    redirect_to login_path, notice: "You're account has been confirmed."
  end

  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.with(user: @user, url: params[:user][:url]).confirm_account.deliver_later
      redirect_to login_path, notice: "An email was sent to your email account."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'User was updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil if current_user == @user
    @user.destroy
    redirect_to users_path, notice: 'User was successfully deleted.'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def same_user?
    redirect_to users_path if @user != current_user && !current_user.profile.superadmin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<section class="flex flex-col m-20 px-10 border-2 border-gray-200 items-center justify-center rounded-lg">
  <h1 class="main-title"><%= title %></h1>

  <div class="mb-10 w-full">
    <%= form_with(model: @user, class: "flex flex-col w-full") do |form| %>

      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
          <%= form.label :email, class: "label-form" %>
          <%= form.email_field :email, class: "field-form" %>
      </div>

      <div>
        <%= form.hidden_field :url, id: "url_field" %>
      </div>

      <div>
          <%= form.label :password, class: "label-form" %>
          <%= form.password_field :password, class: "field-form" %>
      </div>

      <div>
          <%= form.label :password_confirmation, class: "label-form" %>
          <%= form.password_field :password_confirmation, class: "field-form" %>
      </div>

      <div>
      <div class="mt-10 flex justify-center items-center">
        <%= form.submit buttonText, class: "btn-primary bg-green-800" %>
      </div>
    <% end %>
  </div>
</section>

app/views/users/_user.html.erb
<div class="my-10 p-10 border-2 border-green-200 flex flex-col rounded-lg">
    <span class="font-bold text-2xl">
        <%= profile.name %>
    </span>

    <span class="font-bold text-xs">
        <%= profile.user.email %> <br>
    </span>

    <span class="font-semibold">
        <%= profile.country %>
    </span>

    <div class="my-3">
        <%= link_to 'See user', profile_path(profile), class:"btn-primary bg-green-900" %>
    </div>
</div>

app/views/users/edit.html.erb
<%= render 'form', {buttonText: 'Update account', title: 'Edit account'} %>

app/views/users/index.html.erb
<section class="m-10 p-5">
    <h1 class="main-title">Users</h1>

    <% @users.each do |user| %>
        <%= render 'user', profile: user.profile %>
    <% end %>
</section>

app/views/users/new.html.erb
<%= render 'form', {buttonText: 'Sign Up', title: 'Sign Up'} %>
<%= javascript_include_tag "url.js" %>

app/views/users/show.html.erb
<h1>User</h1>

<div>
    <%= @user.email %> <br>
    <%= link_to 'Edit User', user_edit_path(@user) %> <br>
    <%= button_to 'Delete User', user_destroy_path(@user), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } } %>
</div>