config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: %i[create destroy]
  resources :categories
  resources :profiles

  get '/confirm_email/:token', to: 'users#confirm_email'
  delete '/logout', to: "sessions#destroy", as: 'logout'

  post '/login', to: "sessions#create", as: 'new_user_session'
  get '/login', to: "sessions#login", as: 'login'

  delete "/user/:id", to: "users#destroy", as: "user_destroy"
  patch "/user/:id", to: "users#update"
  get "/user/:id/edit", to: "users#edit", as: "user_edit"
  get "/user/:id", to: "users#show", as: "user"
  post '/users', to: "users#create"
  get '/signup', to: "users#new", as: "signup"
  get '/users', to: 'users#index'

  delete "/article/:id", to: "articles#destroy", as: "article_destroy"
  patch "/article/:id", to: "articles#update"
  get "/article/:id/edit", to: "articles#edit", as: "article_edit"
  get "/article/:id", to: "articles#show", as: "article"
  get "/articles/new", to: "articles#new"
  post "/articles", to: "articles#create"
  get "/articles", to: "articles#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/views/shared/_header.html.erb
<nav class="flex justify-between p-3 bg-blue-900">
  <ul class="flex gap-2 items-center">
    <li class="font-bold text-lg text-white"> <%= link_to 'Rails App', root_path %> </li>
    <% if current_user && current_user.profile.present? %>
      <li> <%= link_to 'Articles', articles_path, class: "btn-primary" %> </li>
      <li> <%= link_to 'Users', users_path, class: "btn-primary" %> </li>
      <li> <%= link_to 'Categories', categories_path, class: "btn-primary" %> </li>
      <li class="font-bold text-white"> <%= current_user.profile.role %> </li>
      <% unless current_user.profile.member? %>
        <li> <%= link_to "New category", new_category_path, class:"btn-primary" %> </li>
        <li> <%= link_to 'New article', articles_new_path, class: "btn-primary" %> </li>
      <% end %>
    <% end %>
  </ul>

  <ul class="flex gap-2 items-center">
    <% if current_user %>
      <li> <%= button_to 'Log out', logout_path, method: :delete, class: "btn-primary bg-red-700" %> </li>
      <li class="text-white text-sm font-semibold"> <%= current_user.email %> </li>
    <% else %>
      <li> <%= link_to 'Login', login_path, class: "btn-primary bg-green-700" %> </li>
      <li> <%= link_to 'Sign Up', signup_path, class: "btn-primary bg-blue-600" %> </li>
    <% end %>
  </ul>
</nav>